engines:
    duplication:
        enabled: false
        config:
            languages:
                - javascript
    fixme:
        enabled: true
    eslint:
        enabled: true

exclude_paths:
    - src/debug.js
